services:
  app:
    build: .
    ports:
      - ${PORT}:${PORT}
    environment:
      DB_HOST: db
    depends_on:
      db:
        condition: service_healthy
        restart: true
    volumes:
      - .:/usr/app

  db:
    image: mysql:lts
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p${DB_PASSWORD}']
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - ./db_data:/var/lib/mysql
