// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from 'dotenv';
import { join } from 'node:path';
import { defineConfig } from 'prisma/config';

const env = process.env.NODE_ENV ?? '';

const envFileNames = {
  development: '.env.development.local',
  production: '.env',
};

config({
  path: env in envFileNames ? envFileNames[env] : envFileNames.production,
  override: true,
});

const dbUrl = (() => {
  const url = new URL(`mysql://${process.env.DB_HOST}`);

  url.protocol = 'mysql';
  url.username = process.env.DB_USER ?? '';
  url.password = process.env.DB_PASSWORD ?? '';
  url.host = process.env.DB_HOST ?? '';
  url.port = process.env.DB_PORT ?? '';
  url.pathname = process.env.DB_NAME ?? '';
  url.search = new URLSearchParams({
    'ssl-mode': 'REQUIRED',
    sslcert: join(process.cwd(), 'secret', 'ca.pem'),
  }).toString();

  return url;
})();

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: { url: dbUrl.href },
});
