// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from 'dotenv';
import { defineConfig } from 'prisma/config';

const env = process.env.NODE_ENV ?? '';

const envFileNames = {
  development: '.env.development.local',
  production: '.env',
};

config({
  path: env in envFileNames ? envFileNames[env] : envFileNames.production,
  override: true,
});

const url = `mysql://${process.env.DB_USER}:${process.env.DB_PASSWORD}@${process.env.DB_HOST}:${process.env.DB_PORT}/${process.env.DB_NAME}`;

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: { url },
});
